### ISSUE TITLE
Issues with pysicktim.py

### ISSUE THREAD

**Issue by pol-francesch** [ansarid/pysicktim#3]
Hello,

I am having some issues with running your code on Windows or Linux. First let me ask, is this code made to work "out of the box"? If it is not, that is fine I will start tinkering myself, but otherwise there are some issues I am having which are probably due to my inexperience. 

I am currently trying to interface with a tim561 using Python, and so I found your driver. I installed it as per the instructions on your page, however when I run any of the examples, it either gives no output (such as in the remote_view ones) or gives the following error:

AttributeError: module 'pysicktim' has no attribute 'scan'

I got this one specifically from the test.py file. I was going to just ignore these test files, and use your pysicktim.py file which looks rather nice, however I am having issues with it as you use things which my interpreter says are not initialized like 

connected(),  read(), and lidar.

Am I simply running the wrong things and hence this is causing issues as it is out of order, or is this more of a work in progress?

Thanks in advance, and especially for providing what looks to be a great driver!

**Comment by ansarid** [comment]
Hello!

I'm glad you're trying out my library. Firstly I'll be honest that I wrote this library when I was first learning how this stuff should be done, so there is a lot wrong with how things are done in this library. For example I should bundle all those lidar functions in a lidar class and also there are some things I added as 'features' that are honestly just plain stupid in hindsight. I do plan to rewrite this library soon since I personally do use this library myself and it's the only option outside of ROS.

That being said it is a working library that should function basically out of the box. Firstly I'd want to make sure that you understand that this library was written so that you can use the lidar over its **USB** interface, **not** the ethernet interface. This is because when I wrote this library we were putting this lidar on small mobile robots powered by embedded systems that had USB interfaces but not Ethernet interfaces. This library does not support ethernet at all.

Also this library works best on Linux. It should run on Windows but I've never tried it.

How to run the `scan_example.py` example:

1. Connect the lidar to your device using the microUSB port on the lidar.
2. Install the library with `sudo pip3 install pysicktim`. This reminds me, the code in the github repo is slighly modified and untested, do not install from source.
3. Run `git clone https://github.com/ansarid/pysicktim`.
4. Move into the examples directory. `cd pysicktim/examples`
5. Run `sudo python3 scan_example.py`. You will need to run it with sudo but you can fix this with the udev rules later if you have not done that already.
6. Done... It should be print a large list of data points to the terminal.

How to run the `remote_view` examples:

1. Install matplotlib for python3 on your computer.
2. Download the `tim5xx_client.py` to your computer and open it in a text editor.
3. Change the IP address on line 10 to the IP address of the computer with the lidar. You can set this to `localhost` if you want to run the `tim5xx_client.py` on the same computer as you have the lidar connected to.
4. Run `sudo python3 tim5xx_server.py` on the computer with the lidar connected.
5. Run `python3 tim5xx_client.py` on the computer you installed matplotlib on.
6. Done, you should see the data from the lidar being plotted onto the polar plot.

Let me know if anything here is confusing.

Good luck!

**Comment by pol-francesch** [comment]
Thank you so much for this! My problem was definitely to do with me installing from source, as that is what I did. I will installing from pip later this week, once I can get back to my lab where the lidar is located. Looking forward to any future updates you may make :)

**Comment by ansarid** [comment]
Sounds good. Let me know if you have any other issues. I'll close this once you confirm that it works.

**Comment by pol-francesch** [comment]
Hi,

Sorry for my delay. The implementation with pip works wonders. Thank you so much for your help, and for developing this tool!

**Comment by ansarid** [comment]
No problem! Let me know if you have any issues or recommendations!
